// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BpeProducts.Services.Course.Host.Tests.Integration
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CourseVersioning")]
    [NUnit.Framework.CategoryAttribute("Api")]
    public partial class CourseVersioningFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CourseVersioning.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CourseVersioning", "In order to allow continuous enhancement of course\r\nAs a course builder\r\nI want t" +
                    "o version the course", ProgrammingLanguage.CSharp, new string[] {
                        "Api"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table1.AddRow(new string[] {
                        "COB"});
#line 8
 testRunner.Given("the following organizations exist", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Capability"});
            table2.AddRow(new string[] {
                        "CourseCreate"});
            table2.AddRow(new string[] {
                        "CoursePublish"});
            table2.AddRow(new string[] {
                        "CourseView"});
#line 11
 testRunner.And("I have the following capabilities", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Instructions",
                        "AssessmentType",
                        "IsPublished",
                        "VersionNumber"});
            table3.AddRow(new string[] {
                        "Assessment1",
                        "Do this",
                        "WrittenWork",
                        "true",
                        "1.1"});
#line 16
 testRunner.And("I have the following assessments", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "Description",
                        "OrganizationName",
                        "CourseType",
                        "IsTemplate"});
            table4.AddRow(new string[] {
                        "English 1010",
                        "ENG101",
                        "Ranji\'s awesome English Class",
                        "COB",
                        "Traditional",
                        "false"});
            table4.AddRow(new string[] {
                        "English 101011",
                        "E10011",
                        "Macroeconomics",
                        "COB",
                        "Traditional",
                        "false"});
#line 19
 testRunner.And("I have the following courses", ((string)(null)), table4, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a default version")]
        public virtual void CreateADefaultVersion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a default version", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Name",
                        "English 1010"});
            table5.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table5.AddRow(new string[] {
                        "Description",
                        "Ranji\'s awesome English Class"});
            table5.AddRow(new string[] {
                        "VersionNumber",
                        "1.0.0.0"});
#line 26
 testRunner.Then("the course \'English 1010\' should have the following info", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit a course version")]
        public virtual void EditACourseVersion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit a course version", ((string[])(null)));
#line 33
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "Name",
                        "English 10101"});
            table6.AddRow(new string[] {
                        "Code",
                        "ENG10101"});
            table6.AddRow(new string[] {
                        "Description",
                        "Ranji\'s terrible English Class"});
            table6.AddRow(new string[] {
                        "IsTemplate",
                        "true"});
#line 34
 testRunner.When("I update \'English 1010\' course with the following info", ((string)(null)), table6, "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "Name",
                        "English 10101"});
            table7.AddRow(new string[] {
                        "Code",
                        "ENG10101"});
            table7.AddRow(new string[] {
                        "Description",
                        "Ranji\'s terrible English Class"});
            table7.AddRow(new string[] {
                        "VersionNumber",
                        "1.0.0.0"});
            table7.AddRow(new string[] {
                        "OrganizationName",
                        "COB"});
            table7.AddRow(new string[] {
                        "IsTemplate",
                        "true"});
#line 40
 testRunner.Then("the course \'English 1010\' should have the following info", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Publish a course version")]
        public virtual void PublishACourseVersion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Publish a course version", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table8.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 50
 testRunner.When("I publish the following courses", ((string)(null)), table8, "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "Name",
                        "English 1010"});
            table9.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table9.AddRow(new string[] {
                        "Description",
                        "Ranji\'s awesome English Class"});
            table9.AddRow(new string[] {
                        "VersionNumber",
                        "1.0.0.0"});
            table9.AddRow(new string[] {
                        "IsPublished",
                        "true"});
            table9.AddRow(new string[] {
                        "PublishNote",
                        "Blah blah"});
#line 53
 testRunner.Then("the course \'English 1010\' should have the following info", ((string)(null)), table9, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Course cannot be published when a learning activity does not have an associated a" +
            "ssessment")]
        public virtual void CourseCannotBePublishedWhenALearningActivityDoesNotHaveAnAssociatedAssessment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Course cannot be published when a learning activity does not have an associated a" +
                    "ssessment", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table10.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
#line 66
 testRunner.Given("I have the following course segments for \'English 1010\'", ((string)(null)), table10, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Type",
                        "IsGradeable",
                        "IsExtraCredit",
                        "Weight",
                        "MaxPoint",
                        "ObjectId"});
            table11.AddRow(new string[] {
                        "WrittenWork 1",
                        "WrittenWork",
                        "True",
                        "true",
                        "100",
                        "20",
                        "D2DF063D-E2A1-4F83-9BE0-218EC676C05F"});
#line 69
 testRunner.And("I add the following course learning activities to \'Week1\' course segment", ((string)(null)), table11, "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table12.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 72
 testRunner.When("I publish the following courses", ((string)(null)), table12, "When ");
#line 75
 testRunner.Then("I get \'BadRequest\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Published version cannot be modified")]
        public virtual void PublishedVersionCannotBeModified()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Published version cannot be modified", ((string[])(null)));
#line 78
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table13.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 79
 testRunner.When("I publish the following courses", ((string)(null)), table13, "When ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "Name",
                        "English 10101"});
            table14.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table14.AddRow(new string[] {
                        "Description",
                        "Johns\'s terrible English Class"});
            table14.AddRow(new string[] {
                        "OrganizationId",
                        "E2DF063D-E2A1-4F83-9BE0-218EC676C05F"});
#line 82
 testRunner.And("I update \'English 1010\' course with the following info", ((string)(null)), table14, "And ");
#line 88
 testRunner.Then("I get \'Forbidden\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Published version cannot be deleted")]
        public virtual void PublishedVersionCannotBeDeleted()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Published version cannot be deleted", ((string[])(null)));
#line 90
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table15.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 91
 testRunner.When("I publish the following courses", ((string)(null)), table15, "When ");
#line 94
 testRunner.And("I delete \'English 1010\' course", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.Then("I get \'Forbidden\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a course version from a previously-published version")]
        public virtual void CreateACourseVersionFromAPreviously_PublishedVersion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a course version from a previously-published version", ((string[])(null)));
#line 97
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table16.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 98
 testRunner.When("I publish the following courses", ((string)(null)), table16, "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table17.AddRow(new string[] {
                        "VersionNumber",
                        "2.0a"});
#line 101
 testRunner.And("I create a new version of \'English 1010\' course named \'English 1010 v2\' with the " +
                    "following info", ((string)(null)), table17, "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table18.AddRow(new string[] {
                        "Name",
                        "English 1010"});
            table18.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table18.AddRow(new string[] {
                        "Description",
                        "Ranji\'s awesome English Class"});
            table18.AddRow(new string[] {
                        "VersionNumber",
                        "2.0a"});
            table18.AddRow(new string[] {
                        "IsPublished",
                        "false"});
#line 104
 testRunner.Then("the course \'English 1010 v2\' should have the following info", ((string)(null)), table18, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a course version from a previously-published version then publish it")]
        public virtual void CreateACourseVersionFromAPreviously_PublishedVersionThenPublishIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a course version from a previously-published version then publish it", ((string[])(null)));
#line 112
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table19.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 113
 testRunner.When("I publish the following courses", ((string)(null)), table19, "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table20.AddRow(new string[] {
                        "VersionNumber",
                        "1.0.0.1"});
#line 116
 testRunner.And("I create a new version of \'English 1010\' course named \'English 1010 v1.0.0.1\' wit" +
                    "h the following info", ((string)(null)), table20, "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table21.AddRow(new string[] {
                        "English 1010 v1.0.0.1",
                        "Blah blah DE396"});
#line 119
 testRunner.And("I publish the following courses", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table22.AddRow(new string[] {
                        "Name",
                        "English 1010"});
            table22.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table22.AddRow(new string[] {
                        "Description",
                        "Ranji\'s awesome English Class"});
            table22.AddRow(new string[] {
                        "VersionNumber",
                        "1.0.0.1"});
            table22.AddRow(new string[] {
                        "IsPublished",
                        "true"});
#line 122
 testRunner.Then("the course \'English 1010 v1.0.0.1\' should have the following info", ((string)(null)), table22, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a course version from a previously-published version with prerequisites")]
        public virtual void CreateACourseVersionFromAPreviously_PublishedVersionWithPrerequisites()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a course version from a previously-published version with prerequisites", ((string[])(null)));
#line 130
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table23.AddRow(new string[] {
                        "English 101011",
                        "Blah blah"});
#line 131
 testRunner.When("I publish the following courses", ((string)(null)), table23, "When ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table24.AddRow(new string[] {
                        "English 101011"});
#line 134
 testRunner.And("I add the following prerequisites to \'English 1010\'", ((string)(null)), table24, "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table25.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 137
 testRunner.And("I publish the following courses", ((string)(null)), table25, "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table26.AddRow(new string[] {
                        "VersionNumber",
                        "2.0a"});
#line 140
 testRunner.And("I create a new version of \'English 1010\' course named \'English 1010 v2\' with the " +
                    "following info", ((string)(null)), table26, "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table27.AddRow(new string[] {
                        "Name",
                        "English 1010"});
            table27.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table27.AddRow(new string[] {
                        "Description",
                        "Ranji\'s awesome English Class"});
            table27.AddRow(new string[] {
                        "VersionNumber",
                        "2.0a"});
            table27.AddRow(new string[] {
                        "IsPublished",
                        "false"});
#line 143
 testRunner.Then("the course \'English 1010 v2\' should have the following info", ((string)(null)), table27, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table28.AddRow(new string[] {
                        "English 101011"});
#line 150
 testRunner.And("the course \'English 1010 v2\' should have the following prerequisites", ((string)(null)), table28, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a course version from a previously-published version with segments")]
        public virtual void CreateACourseVersionFromAPreviously_PublishedVersionWithSegments()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a course version from a previously-published version with segments", ((string[])(null)));
#line 154
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table29.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table29.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table29.AddRow(new string[] {
                        "Discussion2",
                        "Discussion2 for the first week",
                        "Discussion",
                        "Week1"});
            table29.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 155
 testRunner.Given("I have the following course segments for \'English 1010\'", ((string)(null)), table29, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table30.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 161
 testRunner.When("I publish the following courses", ((string)(null)), table30, "When ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table31.AddRow(new string[] {
                        "VersionNumber",
                        "2.0a"});
#line 164
 testRunner.And("I create a new version of \'English 1010\' course named \'English 1010 v2\' with the " +
                    "following info", ((string)(null)), table31, "And ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table32.AddRow(new string[] {
                        "Name",
                        "English 1010"});
            table32.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table32.AddRow(new string[] {
                        "Description",
                        "Ranji\'s awesome English Class"});
            table32.AddRow(new string[] {
                        "VersionNumber",
                        "2.0a"});
            table32.AddRow(new string[] {
                        "IsPublished",
                        "false"});
#line 167
 testRunner.Then("the course \'English 1010 v2\' should have the following info", ((string)(null)), table32, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table33.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table33.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table33.AddRow(new string[] {
                        "Discussion2",
                        "Discussion2 for the first week",
                        "Discussion",
                        "Week1"});
            table33.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 174
 testRunner.And("the course \'English 1010 v2\' should have these course segments", ((string)(null)), table33, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a course version from a previously-published version with segments and lea" +
            "rning activities")]
        public virtual void CreateACourseVersionFromAPreviously_PublishedVersionWithSegmentsAndLearningActivities()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a course version from a previously-published version with segments and lea" +
                    "rning activities", ((string[])(null)));
#line 181
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table34.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table34.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table34.AddRow(new string[] {
                        "Discussion2",
                        "Discussion2 for the first week",
                        "Discussion",
                        "Week1"});
            table34.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 182
 testRunner.Given("I have the following course segments for \'English 1010\'", ((string)(null)), table34, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Type",
                        "IsGradeable",
                        "IsExtraCredit",
                        "Weight",
                        "MaxPoint",
                        "ObjectId",
                        "Assessment"});
            table35.AddRow(new string[] {
                        "Discussion 1",
                        "Discussion",
                        "True",
                        "true",
                        "100",
                        "20",
                        "D2DF063D-E2A1-4F83-9BE0-218EC676C05F",
                        ""});
            table35.AddRow(new string[] {
                        "Essay",
                        "WrittenWork",
                        "True",
                        "true",
                        "100",
                        "20",
                        "D2DF063D-E2A1-4F83-9BE0-218EC676C05F",
                        "Assessment1"});
#line 188
 testRunner.And("I add the following course learning activities to \'Week1\' course segment", ((string)(null)), table35, "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table36.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 193
 testRunner.When("I publish the following courses", ((string)(null)), table36, "When ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table37.AddRow(new string[] {
                        "VersionNumber",
                        "2.0a"});
#line 196
 testRunner.And("I create a new version of \'English 1010\' course named \'English 1010 v2\' with the " +
                    "following info", ((string)(null)), table37, "And ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table38.AddRow(new string[] {
                        "Name",
                        "English 1010"});
            table38.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table38.AddRow(new string[] {
                        "Description",
                        "Ranji\'s awesome English Class"});
            table38.AddRow(new string[] {
                        "VersionNumber",
                        "2.0a"});
            table38.AddRow(new string[] {
                        "IsPublished",
                        "false"});
#line 199
 testRunner.Then("the course \'English 1010 v2\' should have the following info", ((string)(null)), table38, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table39.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table39.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table39.AddRow(new string[] {
                        "Discussion2",
                        "Discussion2 for the first week",
                        "Discussion",
                        "Week1"});
            table39.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 206
 testRunner.And("the course \'English 1010 v2\' should have these course segments", ((string)(null)), table39, "And ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table40.AddRow(new string[] {
                        "Name",
                        "Essay"});
            table40.AddRow(new string[] {
                        "Type",
                        "WrittenWork"});
            table40.AddRow(new string[] {
                        "IsGradeable",
                        "true"});
            table40.AddRow(new string[] {
                        "IsExtraCredit",
                        "true"});
            table40.AddRow(new string[] {
                        "Weight",
                        "100"});
            table40.AddRow(new string[] {
                        "MaxPoint",
                        "20"});
            table40.AddRow(new string[] {
                        "ObjectId",
                        "D2DF063D-E2A1-4F83-9BE0-218EC676C05F"});
            table40.AddRow(new string[] {
                        "Assessment",
                        "Assessment1"});
#line 212
 testRunner.And("my course learning activity \'Essay\' contains the following", ((string)(null)), table40, "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table41.AddRow(new string[] {
                        "Name",
                        "Discussion 1"});
            table41.AddRow(new string[] {
                        "Type",
                        "Discussion"});
            table41.AddRow(new string[] {
                        "IsGradeable",
                        "true"});
            table41.AddRow(new string[] {
                        "IsExtraCredit",
                        "true"});
            table41.AddRow(new string[] {
                        "Weight",
                        "100"});
            table41.AddRow(new string[] {
                        "MaxPoint",
                        "20"});
            table41.AddRow(new string[] {
                        "ObjectId",
                        "D2DF063D-E2A1-4F83-9BE0-218EC676C05F"});
#line 222
 testRunner.And("my course learning activity \'Discussion 1\' contains the following", ((string)(null)), table41, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cannot publish the same version twice")]
        public virtual void CannotPublishTheSameVersionTwice()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot publish the same version twice", ((string[])(null)));
#line 232
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table42.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 233
 testRunner.When("I publish the following courses", ((string)(null)), table42, "When ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table43.AddRow(new string[] {
                        "VersionNumber",
                        "1.0.0.0"});
#line 236
 testRunner.And("I create a new version of \'English 1010\' course named \'English 1010 v2\' with the " +
                    "following info", ((string)(null)), table43, "And ");
#line 239
 testRunner.Then("I get \'BadRequest\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cannot publish without a version")]
        public virtual void CannotPublishWithoutAVersion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot publish without a version", ((string[])(null)));
#line 241
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 242
 testRunner.When("I create a course without a version", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 243
 testRunner.Then("I get \'BadRequest\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search for published course")]
        public virtual void SearchForPublishedCourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for published course", ((string[])(null)));
#line 245
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Note"});
            table44.AddRow(new string[] {
                        "English 1010",
                        "Blah blah"});
#line 246
 testRunner.When("I publish the following courses", ((string)(null)), table44, "When ");
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table45.AddRow(new string[] {
                        "English 1010"});
#line 249
 testRunner.Then("published courses for orgniazation \'COB\' contains the following courses", ((string)(null)), table45, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table46.AddRow(new string[] {
                        "English 101011"});
#line 252
 testRunner.And("published courses for orgniazation \'COB\' does not contain the following courses", ((string)(null)), table46, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
