// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18063
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BpeProducts.Services.Course.Host.Tests.Integration
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Course Learning Material")]
    [NUnit.Framework.CategoryAttribute("Api")]
    public partial class CourseLearningMaterialFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CourseLearningMaterial.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Course Learning Material", "", ProgrammingLanguage.CSharp, new string[] {
                        "Api"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table1.AddRow(new string[] {
                        "COB"});
#line 5
 testRunner.Given("the following organizations exist", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Capability"});
            table2.AddRow(new string[] {
                        "CourseCreate"});
            table2.AddRow(new string[] {
                        "CoursePublish"});
            table2.AddRow(new string[] {
                        "CourseView"});
            table2.AddRow(new string[] {
                        "EditCourse"});
#line 8
 testRunner.And("I have the following capabilities", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table3.AddRow(new string[] {
                        "asset1"});
            table3.AddRow(new string[] {
                        "asset2"});
#line 14
 testRunner.And("I have the following assets", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "PublishNote"});
            table4.AddRow(new string[] {
                        "asset1",
                        "published"});
            table4.AddRow(new string[] {
                        "asset2",
                        "published"});
#line 18
 testRunner.And("Published the following assets", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "Description",
                        "OrganizationName",
                        "CourseType",
                        "IsTemplate",
                        "MetaData",
                        "ExtensionAssets"});
            table5.AddRow(new string[] {
                        "Econ 100",
                        "E100",
                        "Macroeconomics",
                        "COB",
                        "Traditional",
                        "False",
                        "{someData}",
                        "asset1,asset2"});
#line 22
 testRunner.And("I have the following courses", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table6.AddRow(new string[] {
                        "Week 1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table6.AddRow(new string[] {
                        "Week 2",
                        "Second week is slack time",
                        "TimeSpan",
                        ""});
            table6.AddRow(new string[] {
                        "Day 1",
                        "First Day is slack time",
                        "TimeSpan",
                        "Week 1"});
#line 25
 testRunner.And("I have the following course segments for \'Econ 100\'", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table7.AddRow(new string[] {
                        "file1"});
            table7.AddRow(new string[] {
                        "file2"});
            table7.AddRow(new string[] {
                        "file3"});
            table7.AddRow(new string[] {
                        "file4"});
#line 30
 testRunner.And("I have the following assets", ((string)(null)), table7, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a learning material")]
        public virtual void CreateALearningMaterial()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a learning material", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table8.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "",
                        "false",
                        "Material A",
                        "CustomAttributeA"});
#line 38
    testRunner.When("Create learning material as the following info", ((string)(null)), table8, "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "CustomAttribute"});
            table9.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "",
                        "false",
                        "CustomAttributeA"});
#line 41
 testRunner.Then("The \'Material A\' learning material has the following info", ((string)(null)), table9, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update a learning material")]
        public virtual void UpdateALearningMaterial()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update a learning material", ((string[])(null)));
#line 45
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table10.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "",
                        "false",
                        "Material A",
                        "CustomAttributeA"});
#line 46
    testRunner.Given("Create learning material as the following info", ((string)(null)), table10, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Instruction",
                        "IsRequired",
                        "CustomAttribute"});
            table11.AddRow(new string[] {
                        "file1",
                        "test instruction",
                        "true",
                        "CustomAttributeAUpdate"});
#line 49
 testRunner.When("Update \'Material A\' learning material as the following info", ((string)(null)), table11, "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "CustomAttribute"});
            table12.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "test instruction",
                        "true",
                        "CustomAttributeAUpdate"});
#line 52
 testRunner.Then("The \'Material A\' learning material has the following info", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete a learning material")]
        public virtual void DeleteALearningMaterial()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete a learning material", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table13.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "",
                        "false",
                        "Material A",
                        "CustomAttributeA"});
#line 57
    testRunner.Given("Create learning material as the following info", ((string)(null)), table13, "Given ");
#line 60
 testRunner.When("I remove \'Material A\' learning material", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.And("I retrieve the learning material \'Material A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.Then("I get \'NotFound\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create learning materials with same asset")]
        public virtual void CreateLearningMaterialsWithSameAsset()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create learning materials with same asset", ((string[])(null)));
#line 64
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "LearningMaterial",
                        "Instruction",
                        "IsRequired",
                        "CustomAttribute"});
            table14.AddRow(new string[] {
                        "file2",
                        "Week 1",
                        "Material A",
                        "",
                        "false",
                        "CustomAttributeA"});
            table14.AddRow(new string[] {
                        "file2",
                        "Week 2",
                        "Material B",
                        "",
                        "false",
                        "CustomAttributeB"});
#line 65
    testRunner.When("Create learning material as the following info", ((string)(null)), table14, "When ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "LearningMaterial",
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "CustomAttribute"});
            table15.AddRow(new string[] {
                        "Material A",
                        "file2",
                        "Week 1",
                        "",
                        "false",
                        "CustomAttributeA"});
            table15.AddRow(new string[] {
                        "Material B",
                        "file2",
                        "Week 2",
                        "",
                        "false",
                        "CustomAttributeB"});
#line 69
 testRunner.Then("The following learning materials have the following info", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can create a section from the course with learning materials")]
        public virtual void CanCreateASectionFromTheCourseWithLearningMaterials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can create a section from the course with learning materials", ((string[])(null)));
#line 74
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "PublishNote"});
            table16.AddRow(new string[] {
                        "file1",
                        "published"});
            table16.AddRow(new string[] {
                        "file2",
                        "published"});
#line 75
 testRunner.Given("Published the following assets", ((string)(null)), table16, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table17.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "",
                        "false",
                        "Material A",
                        "CustomAttributeA"});
            table17.AddRow(new string[] {
                        "file2",
                        "Week 2",
                        "",
                        "false",
                        "Material B",
                        "CustomAttributeB"});
#line 79
    testRunner.And("Create learning material as the following info", ((string)(null)), table17, "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "CourseName",
                        "Note"});
            table18.AddRow(new string[] {
                        "Econ 100",
                        "published"});
#line 83
 testRunner.And("Publish the following courses", ((string)(null)), table18, "And ");
#line 86
 testRunner.When("The section service returns \'Created\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "CourseName",
                        "Name",
                        "Code",
                        "StartDate",
                        "EndDate",
                        "OrganizationName"});
            table19.AddRow(new string[] {
                        "Econ 100",
                        "Econ 100 Section",
                        "Test Code",
                        "2/15/2014",
                        "6/15/2014",
                        "COB"});
#line 87
 testRunner.And("Create section as following", ((string)(null)), table19, "And ");
#line 90
    testRunner.Then("I get \'Created\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a course from a course template with learning materials")]
        public virtual void CreateACourseFromACourseTemplateWithLearningMaterials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a course from a course template with learning materials", ((string[])(null)));
#line 92
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "Description",
                        "OrganizationName",
                        "CourseType",
                        "IsTemplate",
                        "MetaData",
                        "ExtensionAssets"});
            table20.AddRow(new string[] {
                        "English Template",
                        "TemplateCode1",
                        "English Class Template",
                        "COB",
                        "Traditional",
                        "true",
                        "{someData}",
                        "asset1,asset2"});
#line 93
   testRunner.Given("I have the following course templates", ((string)(null)), table20, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table21.AddRow(new string[] {
                        "Week one",
                        "First week",
                        "TimeSpan",
                        ""});
            table21.AddRow(new string[] {
                        "Week two",
                        "Second week",
                        "TimeSpan",
                        ""});
            table21.AddRow(new string[] {
                        "Day one",
                        "First Day",
                        "TimeSpan",
                        "Week one"});
#line 96
    testRunner.And("I have the following course segments for \'English Template\'", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table22.AddRow(new string[] {
                        "file1",
                        "Week one",
                        "",
                        "false",
                        "Template Material A",
                        "CustomAttributeA"});
            table22.AddRow(new string[] {
                        "file2",
                        "Week two",
                        "test  instruction",
                        "true",
                        "Template Material B",
                        "CustomAttributeB"});
            table22.AddRow(new string[] {
                        "file3",
                        "Day one",
                        "test  instruction",
                        "true",
                        "Template Material C",
                        "CustomAttributeC"});
#line 101
    testRunner.And("Create learning material as the following info", ((string)(null)), table22, "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Course",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table23.AddRow(new string[] {
                        "file4",
                        "English Template",
                        "",
                        "false",
                        "Template Material D",
                        "CustomAttributeD"});
#line 106
    testRunner.And("Create learning material as the following info", ((string)(null)), table23, "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "Description",
                        "OrganizationName",
                        "IsTemplate"});
            table24.AddRow(new string[] {
                        "English Course",
                        "ENG 200",
                        "My First Course from Template",
                        "COB",
                        "false"});
#line 109
 testRunner.When("Create a course from the template \'English Template\' with the following", ((string)(null)), table24, "When ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "ParentCourse",
                        "CustomAttribute"});
            table25.AddRow(new string[] {
                        "file1",
                        "Week one",
                        "",
                        "false",
                        "English Template",
                        "CustomAttributeA"});
            table25.AddRow(new string[] {
                        "file2",
                        "Week two",
                        "test  instruction",
                        "true",
                        "English Template",
                        "CustomAttributeB"});
            table25.AddRow(new string[] {
                        "file3",
                        "Day one",
                        "test  instruction",
                        "true",
                        "English Template",
                        "CustomAttributeC"});
            table25.AddRow(new string[] {
                        "file4",
                        "",
                        "",
                        "false",
                        "English Template",
                        "CustomAttributeD"});
#line 112
 testRunner.Then("The course \'English Course\' has following learning material", ((string)(null)), table25, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a course version from a previously-published version with learning materia" +
            "ls")]
        public virtual void CreateACourseVersionFromAPreviously_PublishedVersionWithLearningMaterials()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a course version from a previously-published version with learning materia" +
                    "ls", ((string[])(null)));
#line 119
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "PublishNote"});
            table26.AddRow(new string[] {
                        "file1",
                        "published"});
            table26.AddRow(new string[] {
                        "file2",
                        "published"});
            table26.AddRow(new string[] {
                        "file3",
                        "published"});
            table26.AddRow(new string[] {
                        "file4",
                        "published"});
#line 120
 testRunner.Given("Published the following assets", ((string)(null)), table26, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table27.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "instruction 1",
                        "true",
                        "Material A",
                        "CustomAttributeA"});
            table27.AddRow(new string[] {
                        "file2",
                        "Week 2",
                        "instruction 2",
                        "false",
                        "Material B",
                        "CustomAttributeB"});
            table27.AddRow(new string[] {
                        "file3",
                        "Day 1",
                        "instruction 3",
                        "true",
                        "Material C",
                        "CustomAttributeC"});
#line 126
    testRunner.And("Create learning material as the following info", ((string)(null)), table27, "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Course",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table28.AddRow(new string[] {
                        "file4",
                        "Econ 100",
                        "instruction 4",
                        "true",
                        "Material D",
                        "CustomAttributeD"});
#line 131
 testRunner.And("Create learning material as the following info", ((string)(null)), table28, "And ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "CourseName",
                        "Note"});
            table29.AddRow(new string[] {
                        "Econ 100",
                        "published"});
#line 134
 testRunner.And("Publish the following courses", ((string)(null)), table29, "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table30.AddRow(new string[] {
                        "VersionNumber",
                        "1.0.0.1"});
#line 137
 testRunner.When("Create a new version of \'Econ 100\' course named \'Econ 100 v1.0.0.1\' with the foll" +
                    "owing info", ((string)(null)), table30, "When ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "ParentCourse",
                        "CustomAttribute"});
            table31.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "instruction 1",
                        "true",
                        "Econ 100",
                        "CustomAttributeA"});
            table31.AddRow(new string[] {
                        "file2",
                        "Week 2",
                        "instruction 2",
                        "false",
                        "Econ 100",
                        "CustomAttributeB"});
            table31.AddRow(new string[] {
                        "file3",
                        "Day 1",
                        "instruction 3",
                        "true",
                        "Econ 100",
                        "CustomAttributeC"});
            table31.AddRow(new string[] {
                        "file4",
                        "",
                        "instruction 4",
                        "true",
                        "Econ 100",
                        "CustomAttributeD"});
#line 140
 testRunner.Then("The course \'Econ 100 v1.0.0.1\' has following learning material", ((string)(null)), table31, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Publish course with learning materials then the associate assets need publish")]
        public virtual void PublishCourseWithLearningMaterialsThenTheAssociateAssetsNeedPublish()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Publish course with learning materials then the associate assets need publish", ((string[])(null)));
#line 147
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "LearningMaterial",
                        "Instruction",
                        "IsRequired",
                        "CustomAttribute"});
            table32.AddRow(new string[] {
                        "file1",
                        "Week 1",
                        "Material A",
                        "",
                        "false",
                        "CustomAttributeA"});
#line 148
    testRunner.Given("Create learning material as the following info", ((string)(null)), table32, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "CourseName",
                        "Note"});
            table33.AddRow(new string[] {
                        "Econ 100",
                        "published"});
#line 151
 testRunner.When("Publish the following courses with \'file1\' asset does not publish", ((string)(null)), table33, "When ");
#line 154
 testRunner.Then("The asset \'file1\' is published", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a course learning material")]
        public virtual void CreateACourseLearningMaterial()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a course learning material", ((string[])(null)));
#line 158
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Course",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table34.AddRow(new string[] {
                        "file1",
                        "Econ 100",
                        "",
                        "false",
                        "Material A",
                        "CustomAttributeA"});
#line 159
    testRunner.When("Create learning material as the following info", ((string)(null)), table34, "When ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Course",
                        "Instruction",
                        "IsRequired",
                        "CustomAttribute"});
            table35.AddRow(new string[] {
                        "file1",
                        "Econ 100",
                        "",
                        "false",
                        "CustomAttributeA"});
#line 162
 testRunner.Then("The \'Material A\' learning material has the following info", ((string)(null)), table35, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update a course learning material")]
        public virtual void UpdateACourseLearningMaterial()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update a course learning material", ((string[])(null)));
#line 166
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Course",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table36.AddRow(new string[] {
                        "file1",
                        "Econ 100",
                        "",
                        "false",
                        "Material A",
                        "CustomAttributeA"});
#line 167
    testRunner.Given("Create learning material as the following info", ((string)(null)), table36, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Instruction",
                        "IsRequired",
                        "CustomAttribute"});
            table37.AddRow(new string[] {
                        "file1",
                        "test instruction",
                        "true",
                        "CustomAttributeAUpdate"});
#line 170
 testRunner.When("Update \'Material A\' learning material as the following info", ((string)(null)), table37, "When ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Course",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table38.AddRow(new string[] {
                        "file1",
                        "Econ 100",
                        "test instruction",
                        "true",
                        "Material A",
                        "CustomAttributeA"});
#line 173
 testRunner.Then("The \'Material A\' learning material has the following info", ((string)(null)), table38, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete a course learning material")]
        public virtual void DeleteACourseLearningMaterial()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete a course learning material", ((string[])(null)));
#line 177
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "Course",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table39.AddRow(new string[] {
                        "file1",
                        "Econ 100",
                        "",
                        "false",
                        "Material A",
                        "CustomAttributeA"});
#line 178
    testRunner.Given("Create learning material as the following info", ((string)(null)), table39, "Given ");
#line 181
 testRunner.When("I remove \'Material A\' learning material", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 182
 testRunner.And("I retrieve the learning material \'Material A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 183
 testRunner.Then("I get \'NotFound\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Can not create a learning material with empty assetId")]
        public virtual void CanNotCreateALearningMaterialWithEmptyAssetId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Can not create a learning material with empty assetId", ((string[])(null)));
#line 185
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Asset",
                        "CourseSegment",
                        "Instruction",
                        "IsRequired",
                        "LearningMaterial",
                        "CustomAttribute"});
            table40.AddRow(new string[] {
                        "",
                        "Week 1",
                        "",
                        "false",
                        "Material A",
                        "CustomAttributeA"});
#line 186
    testRunner.When("Create learning material as the following info", ((string)(null)), table40, "When ");
#line 189
 testRunner.Then("I get \'BadRequest\' response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
