// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18052
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BpeProducts.Services.Course.Host.Tests.Integration
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CourseSegment")]
    [NUnit.Framework.CategoryAttribute("Api")]
    public partial class CourseSegmentFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CourseSegment.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CourseSegment", "In order to structure my course\r\nAs a curriculum coordinator\r\nI want to add segme" +
                    "nts to the course", ProgrammingLanguage.CSharp, new string[] {
                        "Api"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "Description",
                        "OrganizationId"});
            table1.AddRow(new string[] {
                        "Math 101",
                        "M101",
                        "Basic mathematics",
                        "E2DF063D-E2A1-4F83-9BE0-218EC676C05F"});
#line 8
 testRunner.Given("I have the following courses", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add course segment")]
        public virtual void AddCourseSegment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add course segment", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table2.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table2.AddRow(new string[] {
                        "Week2",
                        "Second week is more slack time",
                        "TimeSpan",
                        ""});
#line 13
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table3.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table3.AddRow(new string[] {
                        "Week2",
                        "Second week is more slack time",
                        "TimeSpan",
                        ""});
#line 17
 testRunner.Then("the course \'Math 101\' should have these course segments", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add a nested course segment")]
        public virtual void AddANestedCourseSegment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a nested course segment", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table4.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table4.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table4.AddRow(new string[] {
                        "Discussion2",
                        "Discussion2 for the first week",
                        "Discussion",
                        "Week1"});
            table4.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 23
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table4, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table5.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table5.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table5.AddRow(new string[] {
                        "Discussion2",
                        "Discussion2 for the first week",
                        "Discussion",
                        "Week1"});
            table5.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 29
 testRunner.Then("the course \'Math 101\' should have these course segments", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update the course segment info without affecting the segment tree")]
        public virtual void UpdateTheCourseSegmentInfoWithoutAffectingTheSegmentTree()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update the course segment info without affecting the segment tree", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table6.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table6.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table6.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 37
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table6, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type"});
            table7.AddRow(new string[] {
                        "Discussion",
                        "Discussion is important",
                        "Discussion"});
            table7.AddRow(new string[] {
                        "Topic",
                        "New Topic for a discussion",
                        "Topic"});
#line 42
 testRunner.When("I update the course segments as follows", ((string)(null)), table7, "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table8.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table8.AddRow(new string[] {
                        "Discussion",
                        "Discussion is important",
                        "Discussion",
                        "Week1"});
            table8.AddRow(new string[] {
                        "Topic",
                        "New Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 46
 testRunner.Then("the course \'Math 101\' should have these course segments", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve the course segment tree from anywhere in the structure")]
        public virtual void RetrieveTheCourseSegmentTreeFromAnywhereInTheStructure()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve the course segment tree from anywhere in the structure", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table9.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table9.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table9.AddRow(new string[] {
                        "Discussion2",
                        "Discussion2 for the first week",
                        "Discussion",
                        "Week1"});
            table9.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic",
                        "Discussion"});
#line 53
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table9, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type"});
            table10.AddRow(new string[] {
                        "Topic",
                        "Topic for a discussion",
                        "Topic"});
#line 59
 testRunner.Then("the course segment \'Discussion\' should have these children segments", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add multiple content to a segment")]
        public virtual void AddMultipleContentToASegment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add multiple content to a segment", ((string[])(null)));
#line 63
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table11.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table11.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
#line 64
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table11, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Type"});
            table12.AddRow(new string[] {
                        "10257797-ab74-4796-a2f7-4722f8f96abe",
                        "Discussion"});
            table12.AddRow(new string[] {
                        "806f8cc4-ed16-4a1b-b8f2-1df373b7631a",
                        "Assignment"});
#line 68
 testRunner.When("I add the following content to \'Discussion\' segment", ((string)(null)), table12, "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Type"});
            table13.AddRow(new string[] {
                        "10257797-ab74-4796-a2f7-4722f8f96abe",
                        "Discussion"});
            table13.AddRow(new string[] {
                        "806f8cc4-ed16-4a1b-b8f2-1df373b7631a",
                        "Assignment"});
#line 72
 testRunner.Then("the course segment \'Discussion\' should have this content", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add another parent segment to a course")]
        public virtual void AddAnotherParentSegmentToACourse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add another parent segment to a course", ((string[])(null)));
#line 77
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table14.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table14.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table14.AddRow(new string[] {
                        "Week2",
                        "second week",
                        "Topic",
                        ""});
#line 78
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table14, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table15.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table15.AddRow(new string[] {
                        "Discussion",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table15.AddRow(new string[] {
                        "Week2",
                        "second week",
                        "Topic",
                        ""});
#line 83
 testRunner.Then("the course \'Math 101\' should have these course segments", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check segment tree is loaded")]
        public virtual void CheckSegmentTreeIsLoaded()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check segment tree is loaded", ((string[])(null)));
#line 89
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment"});
            table16.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        ""});
            table16.AddRow(new string[] {
                        "Week2",
                        "second week",
                        "Topic",
                        ""});
            table16.AddRow(new string[] {
                        "Discussion1",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table16.AddRow(new string[] {
                        "Discussion2",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1"});
            table16.AddRow(new string[] {
                        "Discussion1.1",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1"});
            table16.AddRow(new string[] {
                        "Discussion1.2",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1"});
#line 90
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table16, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment",
                        "ChildCount"});
            table17.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        "",
                        "2"});
            table17.AddRow(new string[] {
                        "Week2",
                        "second week",
                        "Topic",
                        "",
                        "0"});
            table17.AddRow(new string[] {
                        "Discussion1",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1",
                        "2"});
            table17.AddRow(new string[] {
                        "Discussion2",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1",
                        "0"});
            table17.AddRow(new string[] {
                        "Discussion1.1",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1",
                        "0"});
            table17.AddRow(new string[] {
                        "Discussion1.2",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1",
                        "0"});
#line 98
 testRunner.Then("the course \'Math 101\' should have this course segment tree", ((string)(null)), table17, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ensure Course Segment display order is persisted on Save")]
        public virtual void EnsureCourseSegmentDisplayOrderIsPersistedOnSave()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure Course Segment display order is persisted on Save", ((string[])(null)));
#line 107
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment",
                        "DisplayOrder"});
            table18.AddRow(new string[] {
                        "Week2",
                        "second week",
                        "Topic",
                        "",
                        "1"});
            table18.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        "",
                        "0"});
            table18.AddRow(new string[] {
                        "Discussion2",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1",
                        "3"});
            table18.AddRow(new string[] {
                        "Discussion1",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1",
                        "2"});
            table18.AddRow(new string[] {
                        "Discussion1.1",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1",
                        "4"});
            table18.AddRow(new string[] {
                        "Discussion1.2",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1",
                        "5"});
#line 108
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table18, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "DisplayOrder"});
            table19.AddRow(new string[] {
                        "Week1",
                        "0"});
            table19.AddRow(new string[] {
                        "Week2",
                        "1"});
            table19.AddRow(new string[] {
                        "Discussion1",
                        "2"});
            table19.AddRow(new string[] {
                        "Discussion2",
                        "3"});
            table19.AddRow(new string[] {
                        "Discussion1.1",
                        "4"});
            table19.AddRow(new string[] {
                        "Discussion1.2",
                        "5"});
#line 116
 testRunner.Then("The course \'Math 101\' segments retrieved match the display order entered", ((string)(null)), table19, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ensure Course Segment display order is persisted on Update")]
        public virtual void EnsureCourseSegmentDisplayOrderIsPersistedOnUpdate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure Course Segment display order is persisted on Update", ((string[])(null)));
#line 125
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment",
                        "DisplayOrder"});
            table20.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        "",
                        "0"});
            table20.AddRow(new string[] {
                        "Week2",
                        "second week",
                        "Topic",
                        "",
                        "1"});
            table20.AddRow(new string[] {
                        "Discussion1",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1",
                        "2"});
            table20.AddRow(new string[] {
                        "Discussion2",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1",
                        "3"});
            table20.AddRow(new string[] {
                        "Discussion1.1",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1",
                        "4"});
            table20.AddRow(new string[] {
                        "Discussion1.2",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1",
                        "5"});
#line 126
 testRunner.Given("I have the following course segments for \'Math 101\'", ((string)(null)), table20, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "Type",
                        "ParentSegment",
                        "DisplayOrder"});
            table21.AddRow(new string[] {
                        "Week1",
                        "First week is slack time",
                        "TimeSpan",
                        "",
                        "5"});
            table21.AddRow(new string[] {
                        "Week2",
                        "second week",
                        "Topic",
                        "",
                        "4"});
            table21.AddRow(new string[] {
                        "Discussion1",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1",
                        "3"});
            table21.AddRow(new string[] {
                        "Discussion2",
                        "Discussion for the first week",
                        "Discussion",
                        "Week1",
                        "2"});
            table21.AddRow(new string[] {
                        "Discussion1.1",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1",
                        "1"});
            table21.AddRow(new string[] {
                        "Discussion1.2",
                        "Sub Discussion for the first week",
                        "Discussion",
                        "Discussion1",
                        "0"});
#line 134
 testRunner.When("I update the course segments as follows", ((string)(null)), table21, "When ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "DisplayOrder"});
            table22.AddRow(new string[] {
                        "Week1",
                        "5"});
            table22.AddRow(new string[] {
                        "Week2",
                        "4"});
            table22.AddRow(new string[] {
                        "Discussion1",
                        "3"});
            table22.AddRow(new string[] {
                        "Discussion2",
                        "2"});
            table22.AddRow(new string[] {
                        "Discussion1.1",
                        "1"});
            table22.AddRow(new string[] {
                        "Discussion1.2",
                        "0"});
#line 142
 testRunner.Then("The course \'Math 101\' segments retrieved match the display order entered", ((string)(null)), table22, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
