// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BpeProducts.Services.Course.Host.Tests.Integration
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("LearningOutcomeManagement")]
    [NUnit.Framework.CategoryAttribute("Api")]
    public partial class LearningOutcomeManagementFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LearningOutcomeManagement.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "LearningOutcomeManagement", "In order to specify the expected outcome of a course or program\r\nAs a course buil" +
                    "der or program coordinator\r\nI want to manage learning outcomes", ProgrammingLanguage.CSharp, new string[] {
                        "Api"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 21
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Description",
                        "OrganizationId",
                        "TenantId"});
            table1.AddRow(new string[] {
                        "BA",
                        "BA Program",
                        "E2DF063D-E2A1-4F83-9BE0-218EC676C05F",
                        "1"});
#line 22
testRunner.Given("the following programs exist:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "Name",
                        "English 101"});
            table2.AddRow(new string[] {
                        "Code",
                        "ENG101"});
            table2.AddRow(new string[] {
                        "Description",
                        "Ranji\'s awesome English class"});
            table2.AddRow(new string[] {
                        "TenantId",
                        "1"});
            table2.AddRow(new string[] {
                        "OrganizationId",
                        "E2DF063D-E2A1-4F83-9BE0-218EC676C05F"});
#line 25
testRunner.And("the following course exists:", ((string)(null)), table2, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add a new leanring outcome and get it")]
        public virtual void AddANewLeanringOutcomeAndGetIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a new leanring outcome and get it", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line 8
 testRunner.When("I create a learning outcome with the description \'SomeDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("the learning outcome should be with the description \'SomeDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit an existing leanring outcome and get it")]
        public virtual void EditAnExistingLeanringOutcomeAndGetIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit an existing leanring outcome and get it", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line 12
 testRunner.Given("I have a learning outcome with the description \'SomeDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.When("I change the description to \'OtherDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then("the learning outcome should be with the description \'OtherDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Delete an existing leanring outcome")]
        public virtual void DeleteAnExistingLeanringOutcome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete an existing leanring outcome", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line 17
 testRunner.Given("I have a learning outcome with the description \'SomeDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.When("I delete this learning outcome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("the learning outcome shoud no longer exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add a new learning outcome to a program and get it")]
        public virtual void AddANewLearningOutcomeToAProgramAndGetIt()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add a new learning outcome to a program and get it", ((string[])(null)));
#line 33
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line 34
 testRunner.When("I associate to the \'program\' \'BA\' a new learning outcome with the description \'So" +
                    "meDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("the learning outcome should be with the description \'SomeDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.And("the \'program\' \'BA\' is associated with learning outcome \'SomeDescription\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Associate a new learning outcome to a program")]
        public virtual void AssociateANewLearningOutcomeToAProgram()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Associate a new learning outcome to a program", ((string[])(null)));
#line 38
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table3.AddRow(new string[] {
                        "first learning outcome"});
            table3.AddRow(new string[] {
                        "second learning outcome"});
#line 39
testRunner.When("I associate the following learning outcomes to \'BA\' program:", ((string)(null)), table3, "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table4.AddRow(new string[] {
                        "first learning outcome"});
            table4.AddRow(new string[] {
                        "second learning outcome"});
#line 43
testRunner.Then("\'BA\' program is associated with the following learning outcomes:", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Duplicate association is idempotent")]
        public virtual void DuplicateAssociationIsIdempotent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate association is idempotent", ((string[])(null)));
#line 48
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table5.AddRow(new string[] {
                        "first learning outcome"});
#line 49
testRunner.When("I associate the following learning outcomes to \'BA\' program:", ((string)(null)), table5, "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table6.AddRow(new string[] {
                        "first learning outcome"});
#line 52
testRunner.When("I associate the following learning outcomes to \'BA\' program:", ((string)(null)), table6, "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table7.AddRow(new string[] {
                        "first learning outcome"});
#line 55
testRunner.Then("\'BA\' program is associated with the following learning outcomes:", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disassociated a learning outcome from a program")]
        public virtual void DisassociatedALearningOutcomeFromAProgram()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disassociated a learning outcome from a program", ((string[])(null)));
#line 59
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table8.AddRow(new string[] {
                        "first learning outcome"});
            table8.AddRow(new string[] {
                        "second learning outcome"});
#line 60
testRunner.When("I associate the following learning outcomes to \'BA\' program:", ((string)(null)), table8, "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table9.AddRow(new string[] {
                        "first learning outcome"});
#line 64
testRunner.When("I disassociate the following learning outcomes from \'BA\' program:", ((string)(null)), table9, "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table10.AddRow(new string[] {
                        "second learning outcome"});
#line 67
testRunner.Then("\'BA\' program is associated with the only following learning outcomes:", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disassociating non-existing learning outcome")]
        public virtual void DisassociatingNon_ExistingLearningOutcome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disassociating non-existing learning outcome", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table11.AddRow(new string[] {
                        "first learning outcome"});
            table11.AddRow(new string[] {
                        "second learning outcome"});
#line 72
testRunner.When("I associate the following learning outcomes to \'BA\' program:", ((string)(null)), table11, "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Disassociation Response"});
            table12.AddRow(new string[] {
                        "first learning outcome",
                        "NoContent"});
            table12.AddRow(new string[] {
                        "second learning outcome",
                        "NoContent"});
            table12.AddRow(new string[] {
                        "third learning outcome",
                        "NotFound"});
#line 76
testRunner.Then("disassociating the following from \'BA\' program should result:", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Associate an outcome to another outcome")]
        public virtual void AssociateAnOutcomeToAnotherOutcome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Associate an outcome to another outcome", ((string[])(null)));
#line 82
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "TenantId"});
            table13.AddRow(new string[] {
                        "first program learning outcome",
                        "1"});
            table13.AddRow(new string[] {
                        "second program learning outcome",
                        "1"});
#line 83
 testRunner.Given("I associate the following learning outcomes to \'BA\' program:", ((string)(null)), table13, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "TenantId"});
            table14.AddRow(new string[] {
                        "first course learning outcome",
                        "1"});
            table14.AddRow(new string[] {
                        "second course learning outcome",
                        "1"});
#line 87
 testRunner.And("I assoicate the following learning outcomes to \'ENG101\' course:", ((string)(null)), table14, "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "CourseCode",
                        "Description"});
            table15.AddRow(new string[] {
                        "ENG101",
                        "first course learning outcome"});
            table15.AddRow(new string[] {
                        "ENG101",
                        "second course learning outcome"});
#line 91
 testRunner.When("I assoicate the following outcomes to \'second program learning outcome\'", ((string)(null)), table15, "When ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table16.AddRow(new string[] {
                        "first course learning outcome"});
            table16.AddRow(new string[] {
                        "second course learning outcome"});
#line 95
 testRunner.Then("\'second program learning outcome\' has the following learning outcomes:", ((string)(null)), table16, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Disassociate an outcome from another outcome")]
        public virtual void DisassociateAnOutcomeFromAnotherOutcome()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Disassociate an outcome from another outcome", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line 21
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "TenantId"});
            table17.AddRow(new string[] {
                        "first program learning outcome",
                        "1"});
            table17.AddRow(new string[] {
                        "second program learning outcome",
                        "1"});
#line 101
 testRunner.Given("I associate the following learning outcomes to \'BA\' program:", ((string)(null)), table17, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "TenantId"});
            table18.AddRow(new string[] {
                        "first course learning outcome",
                        "1"});
            table18.AddRow(new string[] {
                        "second course learning outcome",
                        "1"});
#line 105
 testRunner.And("I assoicate the following learning outcomes to \'ENG101\' course:", ((string)(null)), table18, "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "CourseCode",
                        "Description"});
            table19.AddRow(new string[] {
                        "ENG101",
                        "first course learning outcome"});
            table19.AddRow(new string[] {
                        "ENG101",
                        "second course learning outcome"});
#line 109
 testRunner.When("I assoicate the following outcomes to \'second program learning outcome\'", ((string)(null)), table19, "When ");
#line 113
 testRunner.And("I disassociate \'first course learning outcome\' from \'second program learning outc" +
                    "ome\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description"});
            table20.AddRow(new string[] {
                        "second course learning outcome"});
#line 114
 testRunner.Then("\'second program learning outcome\' has the following learning outcomes:", ((string)(null)), table20, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
